command:
  calm:
    ## Number of blocks near the player to check for animals to calm
    radius: 16
  info:
    ## Allow certain information to only appear to certain people
    ## - 0: No one can see
    ## - 1: Only owner can see
    ## - 2: Only riders/owner can see
    ## - 3: Everyone can see
    owner: 3
    permitted-riders: 3
    health: 2
    jump-strength: 2
    max-speed: 2
    variant: 3
    ## What is the lowest level people with the bypass permission should see. (Works inversely to the above)
    ## 0 to see everything, 1 to see what an owner would see, etc. (If player is already at 1, bypass as 2 would do nothing)
    bypass-as-level: 0
  release:
    clear-custom-name: false
  rename:
    ## Should the nameplate always be visible, or only when looking at the animal
    name-always-visible: true
aliases:
  addrider:
  - 'add'
  delrider:
  - 'del'
  info:
  - '?'
  teleport:
  - 'tp'
  - 'transport'
protection:
  ## Should stablemaster.bypass.protection always allow damage, else act as if they're the owner
  complete-bypass: false
  ## Protection if the owner hurts the animal
  owner-melee: true
  owner-ranged: false
  ## Protection if another player hurts the animal
  player-melee: true
  player-ranged: true
  ## Protection if a monster hurts the animal
  monster-melee: true
  monster-ranged: true
  ## Protect against projectiles that aren't player or monster
  other-ranged: true
  ## Always protect against these no matter the source
  default:
    block_explosion: true
    contact: true
    cramming: true
    drowning: true
    fall: true
    falling_block: true
    fire: true
    fire_tick: true
    fly_into_wall: true
    hot_floor: true
    lava: true
    lightning: true
    magic: true
    poison: true
    starvation: true
    suffocation: true
    thorns: true
    wither: true